// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\untitled1\Subsystem4.v
// Created: 2023-11-07 21:46:08
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.000113379
// Target subsystem base rate: 0.000113379
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem4
// Source Path: untitled1/Subsystem/Subsystem/Subsystem4
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem4
          (In1,
           In2);


  input   [63:0] In1;  // double
  input   [63:0] In2;  // double




endmodule  // Subsystem4

